version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=L0
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data

  nats-streaming:
    restart: always
    image: nats-streaming:0.25.5-alpine3.18
    ports:
      - 4222:4222
    command:
    - "--cluster_id"
    - "testcluster"
  
  main:
    depends_on:
      - postgres
      - nats-streaming
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: main
    ports:
     - "9090:9090"
    environment:
      HTTP_ADDR: ":9090"
      PG_URL: "postgres://postgres:postgres@postgres/main?sslmode=disable"
      PG_MIGRATIONS_PATH: "file://../../internal/pg/migrations"

    command: ["./main"]